### ISSUE TITLE
Screenshoot

### ISSUE THREAD

**Issue by fabriceyopa** [Doha26/android-google-map-marker-animation#1]
It should be great to have an illustration, it made people more confident about what they are going to see

**Comment by Doha26** [comment]
Hi Fabrice. Don't worry. i will add an illustration and a sample demo. i created this repo today  ( 2h ago) to answer a friend which asked me how to implement it. so don't worry. i will update the repo accordingly.

**Comment by fabriceyopa** [comment]
Great. Go ahead
